import './globals.css';
import {Roboto} from 'next/font/google';

const roboto = Roboto({subsets: ['latin'], weight: ['400']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <head>
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet' />
      </head>
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
